[package]
name = "cougar_question_maker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
better_file_maker = "0.1.9"
txt_writer = "0.1.4"
